### ISSUE TITLE
Does not compile against MariaDB 10.2

### ISSUE THREAD

**Issue by rwmjones** [ygrek/ocaml-mysql#11]
```
checking for mysql_real_connect in -lmysqlclient... mysql_config: unrecognized option '--variable=pkglibdir'
```
This apparently happens because the `mysql_config` tool works differently with MariaDB 10.2, see: https://jira.mariadb.org/browse/MDEV-12938

More information in our downstream tracking bug: https://bugzilla.redhat.com/show_bug.cgi?id=1467652

**Comment by ygrek** [comment]
Thanks for reporting!
Apparently ocaml-mysql configure assumes too much about mysql (e.g. the fact that shared library is called libmysqlclient), will fix.

PS MariaDB issue is about something else and it definitely looks like bug in mysql_config from MariaDB and I hope they will fix it so that there is no need to hardcode linking workarounds in the future (defying the purpose of using `mysql_config` in first place).

**Comment by rwmjones** [comment]
Just FYI, here are the changes planned to MariaDB in Fedora.  It looks as if the upstream code base has decided to fork away from MySQL compatibility:

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/INOGEFLOENPOFZYYTGW2MYFMJMYUK3WP/#DMU2LFMVDYKIYIR3D25QGQ3OTOWV7DD2

**Comment by ygrek** [comment]
Thanks.
afaics they still intend to maintain api compatibility, and with latest change ocaml-mysql now should link against either just fine (it will use whatever mysql_config says).
